import type { SkillDefinition } from '@/lib/engine/types';

export const MATH_SKILLS: SkillDefinition[] = [
  // ─── COUNTING STRAND ───────────────────────────────────────────────
  { code: 'math.counting.to_20', name: 'Count to 20', strandCode: 'counting', level: 0.1,
    prereqSkillCodes: [], curriculumRefs: { ccss: 'K.CC.A.1' },
    themeTags: ['counting', 'insects'], sortOrder: 1 },
  { code: 'math.counting.to_50', name: 'Count to 50', strandCode: 'counting', level: 0.2,
    prereqSkillCodes: ['math.counting.to_20'], curriculumRefs: { ccss: '1.NBT.A.1' },
    themeTags: ['counting', 'plants'], sortOrder: 2 },
  { code: 'math.counting.to_120', name: 'Count to 120', strandCode: 'counting', level: 0.3,
    prereqSkillCodes: ['math.counting.to_50'], curriculumRefs: { ccss: '1.NBT.A.1' },
    themeTags: ['counting', 'plants'], sortOrder: 3 },
  { code: 'math.counting.skip_2s', name: 'Skip count by 2s', strandCode: 'counting', level: 0.3,
    prereqSkillCodes: ['math.counting.to_20'], curriculumRefs: { ccss: '2.NBT.A.2' },
    themeTags: ['counting', 'patterns', 'insects'], sortOrder: 4 },
  { code: 'math.counting.skip_5s', name: 'Skip count by 5s', strandCode: 'counting', level: 0.4,
    prereqSkillCodes: ['math.counting.to_50'], curriculumRefs: { ccss: '2.NBT.A.2' },
    themeTags: ['counting', 'patterns'], sortOrder: 5 },
  { code: 'math.counting.skip_10s', name: 'Skip count by 10s', strandCode: 'counting', level: 0.4,
    prereqSkillCodes: ['math.counting.to_50'], curriculumRefs: { ccss: '2.NBT.A.2' },
    themeTags: ['counting', 'patterns'], sortOrder: 6 },

  // ─── OPERATIONS STRAND — addition ──────────────────────────────────
  { code: 'math.add.within_10', name: 'Add within 10', strandCode: 'operations', level: 0.2,
    prereqSkillCodes: ['math.counting.to_20'], curriculumRefs: { ccss: '1.OA.C.6' },
    themeTags: ['add', 'insects'], sortOrder: 10 },
  { code: 'math.add.within_20.no_crossing', name: 'Add within 20 (no crossing)',
    strandCode: 'operations', level: 0.3,
    prereqSkillCodes: ['math.add.within_10'], curriculumRefs: { ccss: '1.OA.C.6' },
    themeTags: ['add', 'bees'], sortOrder: 11 },
  { code: 'math.add.within_20.crossing_ten', name: 'Add within 20 (crossing ten)',
    strandCode: 'operations', level: 0.45,
    prereqSkillCodes: ['math.add.within_20.no_crossing'], curriculumRefs: { ccss: '1.OA.C.6' },
    themeTags: ['add', 'make_ten', 'butterflies'], sortOrder: 12 },
  { code: 'math.add.fluency_within_20', name: 'Add facts within 20 (fluency)',
    strandCode: 'operations', level: 0.5,
    prereqSkillCodes: ['math.add.within_20.crossing_ten'], curriculumRefs: { ccss: '2.OA.B.2' },
    themeTags: ['add', 'fluency'], sortOrder: 13 },
  { code: 'math.add.within_100.no_regrouping', name: 'Add within 100 (no regrouping)',
    strandCode: 'operations', level: 0.55,
    prereqSkillCodes: ['math.add.within_20.no_crossing'], curriculumRefs: { ccss: '2.NBT.B.5' },
    themeTags: ['add', 'two_digit'], sortOrder: 14 },
  { code: 'math.add.within_100.with_regrouping', name: 'Add within 100 (with regrouping)',
    strandCode: 'operations', level: 0.7,
    prereqSkillCodes: ['math.add.within_100.no_regrouping', 'math.add.within_20.crossing_ten'],
    curriculumRefs: { ccss: '2.NBT.B.5' },
    themeTags: ['add', 'two_digit', 'regrouping'], sortOrder: 15 },

  // ─── OPERATIONS STRAND — subtraction ───────────────────────────────
  { code: 'math.subtract.within_10', name: 'Subtract within 10',
    strandCode: 'operations', level: 0.25,
    prereqSkillCodes: ['math.add.within_10'], curriculumRefs: { ccss: '1.OA.C.6' },
    themeTags: ['subtract', 'flowers'], sortOrder: 20 },
  { code: 'math.subtract.within_20.no_crossing', name: 'Subtract within 20 (no crossing)',
    strandCode: 'operations', level: 0.35,
    prereqSkillCodes: ['math.subtract.within_10'], curriculumRefs: { ccss: '1.OA.C.6' },
    themeTags: ['subtract'], sortOrder: 21 },
  { code: 'math.subtract.within_20.crossing_ten', name: 'Subtract within 20 (crossing ten)',
    strandCode: 'operations', level: 0.5,
    prereqSkillCodes: ['math.subtract.within_20.no_crossing'], curriculumRefs: { ccss: '1.OA.C.6' },
    themeTags: ['subtract', 'make_ten'], sortOrder: 22 },
  { code: 'math.subtract.within_100.no_regrouping', name: 'Subtract within 100 (no regrouping)',
    strandCode: 'operations', level: 0.6,
    prereqSkillCodes: ['math.subtract.within_20.no_crossing'], curriculumRefs: { ccss: '2.NBT.B.5' },
    themeTags: ['subtract', 'two_digit'], sortOrder: 23 },
  { code: 'math.subtract.within_100.with_regrouping', name: 'Subtract within 100 (with regrouping)',
    strandCode: 'operations', level: 0.75,
    prereqSkillCodes: ['math.subtract.within_100.no_regrouping', 'math.subtract.within_20.crossing_ten'],
    curriculumRefs: { ccss: '2.NBT.B.5' },
    themeTags: ['subtract', 'two_digit', 'regrouping'], sortOrder: 24 },

  // ─── NUMBER BONDS / FACT FAMILIES ──────────────────────────────────
  { code: 'math.number_bond.within_10', name: 'Number bonds to 10',
    strandCode: 'operations', level: 0.3,
    prereqSkillCodes: ['math.add.within_10'], curriculumRefs: { ccss: '1.OA.C.6' },
    themeTags: ['bond', 'part_whole'], sortOrder: 30 },
  { code: 'math.number_bond.within_20', name: 'Number bonds to 20',
    strandCode: 'operations', level: 0.45,
    prereqSkillCodes: ['math.number_bond.within_10'], curriculumRefs: { ccss: '1.OA.C.6' },
    themeTags: ['bond', 'part_whole'], sortOrder: 31 },

  // ─── PLACE VALUE ───────────────────────────────────────────────────
  { code: 'math.placevalue.tens_ones', name: 'Place value (tens and ones)',
    strandCode: 'place_value', level: 0.35,
    prereqSkillCodes: ['math.counting.to_50'], curriculumRefs: { ccss: '1.NBT.B.2' },
    themeTags: ['place_value'], sortOrder: 40 },
  { code: 'math.placevalue.hundreds_tens_ones', name: 'Place value (hundreds, tens, ones)',
    strandCode: 'place_value', level: 0.55,
    prereqSkillCodes: ['math.placevalue.tens_ones', 'math.counting.to_120'],
    curriculumRefs: { ccss: '2.NBT.A.1' },
    themeTags: ['place_value', 'three_digit'], sortOrder: 41 },
  { code: 'math.placevalue.compare_2digit', name: 'Compare 2-digit numbers',
    strandCode: 'place_value', level: 0.4,
    prereqSkillCodes: ['math.placevalue.tens_ones'], curriculumRefs: { ccss: '1.NBT.B.3' },
    themeTags: ['compare'], sortOrder: 42 },
  { code: 'math.placevalue.compare_3digit', name: 'Compare 3-digit numbers',
    strandCode: 'place_value', level: 0.6,
    prereqSkillCodes: ['math.placevalue.hundreds_tens_ones'], curriculumRefs: { ccss: '2.NBT.A.4' },
    themeTags: ['compare', 'three_digit'], sortOrder: 43 },
  { code: 'math.placevalue.add_subtract_10', name: '10 more / 10 less',
    strandCode: 'place_value', level: 0.4,
    prereqSkillCodes: ['math.placevalue.tens_ones'], curriculumRefs: { ccss: '1.NBT.C.5' },
    themeTags: ['place_value', 'mental_math'], sortOrder: 44 },

  // ─── MULTIPLICATION FOUNDATIONS ────────────────────────────────────
  { code: 'math.multiply.equal_groups', name: 'Equal groups',
    strandCode: 'multiplication', level: 0.55,
    prereqSkillCodes: ['math.add.within_20.no_crossing', 'math.counting.skip_2s'],
    curriculumRefs: { ccss: '2.OA.C.3' },
    themeTags: ['multiply', 'groups', 'insects'], sortOrder: 50 },
  { code: 'math.multiply.arrays', name: 'Arrays (rows and columns)',
    strandCode: 'multiplication', level: 0.6,
    prereqSkillCodes: ['math.multiply.equal_groups'], curriculumRefs: { ccss: '2.OA.C.4' },
    themeTags: ['multiply', 'arrays', 'ants'], sortOrder: 51 },
  { code: 'math.multiply.skip_count_bridge', name: 'Skip count → multiplication',
    strandCode: 'multiplication', level: 0.6,
    prereqSkillCodes: ['math.counting.skip_2s', 'math.counting.skip_5s'],
    curriculumRefs: { ccss: '3.OA.A.1' },
    themeTags: ['multiply', 'patterns'], sortOrder: 52 },

  // ─── EVEN / ODD ────────────────────────────────────────────────────
  { code: 'math.even_odd.recognize', name: 'Even and odd numbers',
    strandCode: 'place_value', level: 0.45,
    prereqSkillCodes: ['math.counting.skip_2s'], curriculumRefs: { ccss: '2.OA.C.3' },
    themeTags: ['even_odd', 'patterns'], sortOrder: 45 },

  // ─── TIME (Grade 2) ────────────────────────────────────────────────
  { code: 'math.time.read_hour_half', name: 'Read clocks (hour and half-hour)',
    strandCode: 'measurement', level: 0.4,
    prereqSkillCodes: ['math.counting.to_50'], curriculumRefs: { ccss: '1.MD.B.3' },
    themeTags: ['time', 'clock'], sortOrder: 70 },
  { code: 'math.time.read_to_5_min', name: 'Read clocks to the nearest 5 minutes',
    strandCode: 'measurement', level: 0.55,
    prereqSkillCodes: ['math.time.read_hour_half', 'math.counting.skip_5s'],
    curriculumRefs: { ccss: '2.MD.C.7' },
    themeTags: ['time', 'clock', 'skip_5'], sortOrder: 71 },

  // ─── MONEY (Grade 2) ───────────────────────────────────────────────
  { code: 'math.money.coin_count', name: 'Count coins (pennies, nickels, dimes, quarters)',
    strandCode: 'measurement', level: 0.5,
    prereqSkillCodes: ['math.counting.skip_5s', 'math.counting.skip_10s'],
    curriculumRefs: { ccss: '2.MD.C.8' },
    themeTags: ['money', 'coins', 'skip_count'], sortOrder: 72 },

  // ─── MULTIPLICATION (Visual variants) ──────────────────────────────
  // Already had math.multiply.equal_groups + .arrays as text-only
  // EquationTap items. These are the SAME skills but the visual
  // renderers — we add the items at the same skill codes so the
  // adaptive picker can rotate text and visual presentations of the
  // same concept.
  // (No new skill rows here; the visual items reuse the existing
  // multiplication skills.)

  // ─── FRACTIONS (Grade 3 — first push) ──────────────────────────────
  { code: 'math.fractions.identify', name: 'Name the fraction shaded',
    strandCode: 'measurement', level: 0.7,
    prereqSkillCodes: ['math.multiply.equal_groups'],
    curriculumRefs: { ccss: '3.NF.A.1' },
    themeTags: ['fractions', 'parts_whole', 'visual'], sortOrder: 80 },
  { code: 'math.fractions.compare_visual', name: 'Compare fractions (visual)',
    strandCode: 'measurement', level: 0.78,
    prereqSkillCodes: ['math.fractions.identify'],
    curriculumRefs: { ccss: '3.NF.A.3.d' },
    themeTags: ['fractions', 'compare', 'visual'], sortOrder: 81 },

  // ─── GRADE 3 — multiplication facts (3.OA.C.7) ─────────────────────
  { code: 'math.multiply.facts_to_5', name: 'Multiplication facts (×0–×5)',
    strandCode: 'multiplication', level: 0.65,
    prereqSkillCodes: ['math.multiply.equal_groups', 'math.multiply.arrays'],
    curriculumRefs: { ccss: '3.OA.C.7' },
    themeTags: ['multiply', 'facts', 'fluency'], sortOrder: 53 },
  { code: 'math.multiply.facts_to_10', name: 'Multiplication facts (×0–×10)',
    strandCode: 'multiplication', level: 0.78,
    prereqSkillCodes: ['math.multiply.facts_to_5'],
    curriculumRefs: { ccss: '3.OA.C.7' },
    themeTags: ['multiply', 'facts', 'fluency'], sortOrder: 54 },

  // ─── GRADE 3 — division (3.OA.A.2 / 3.OA.B.6 / 3.OA.C.7) ──────────
  { code: 'math.divide.equal_share', name: 'Share equally',
    strandCode: 'multiplication', level: 0.7,
    prereqSkillCodes: ['math.multiply.equal_groups'],
    curriculumRefs: { ccss: '3.OA.A.2' },
    themeTags: ['divide', 'share', 'visual'], sortOrder: 55 },
  { code: 'math.divide.facts_to_10', name: 'Division facts (within 100)',
    strandCode: 'multiplication', level: 0.8,
    prereqSkillCodes: ['math.multiply.facts_to_10', 'math.divide.equal_share'],
    curriculumRefs: { ccss: '3.OA.C.7' },
    themeTags: ['divide', 'facts', 'fluency'], sortOrder: 56 },
  { code: 'math.divide.unknown_factor', name: 'Find the missing factor',
    strandCode: 'multiplication', level: 0.82,
    prereqSkillCodes: ['math.multiply.facts_to_10'],
    curriculumRefs: { ccss: '3.OA.B.6' },
    themeTags: ['multiply', 'divide', 'algebra_thinking'], sortOrder: 57 },

  // ─── GRADE 3 — 3-digit add/subtract (3.NBT.A.2) ────────────────────
  { code: 'math.add.within_1000', name: 'Add within 1000 (3-digit)',
    strandCode: 'operations', level: 0.82,
    prereqSkillCodes: ['math.add.within_100.with_regrouping', 'math.placevalue.hundreds_tens_ones'],
    curriculumRefs: { ccss: '3.NBT.A.2' },
    themeTags: ['add', 'three_digit'], sortOrder: 16 },
  { code: 'math.subtract.within_1000', name: 'Subtract within 1000 (3-digit)',
    strandCode: 'operations', level: 0.85,
    prereqSkillCodes: ['math.subtract.within_100.with_regrouping', 'math.placevalue.hundreds_tens_ones'],
    curriculumRefs: { ccss: '3.NBT.A.2' },
    themeTags: ['subtract', 'three_digit'], sortOrder: 25 },

  // ─── GRADE 3 — rounding (3.NBT.A.1) ────────────────────────────────
  { code: 'math.placevalue.round_nearest_10', name: 'Round to the nearest 10',
    strandCode: 'place_value', level: 0.7,
    prereqSkillCodes: ['math.placevalue.tens_ones'],
    curriculumRefs: { ccss: '3.NBT.A.1' },
    themeTags: ['rounding', 'place_value'], sortOrder: 46 },
  { code: 'math.placevalue.round_nearest_100', name: 'Round to the nearest 100',
    strandCode: 'place_value', level: 0.78,
    prereqSkillCodes: ['math.placevalue.hundreds_tens_ones', 'math.placevalue.round_nearest_10'],
    curriculumRefs: { ccss: '3.NBT.A.1' },
    themeTags: ['rounding', 'place_value', 'three_digit'], sortOrder: 47 },

  // ─── GRADE 3 — elapsed time (3.MD.A.1) ─────────────────────────────
  { code: 'math.time.elapsed_intervals', name: 'How much time has passed?',
    strandCode: 'measurement', level: 0.78,
    prereqSkillCodes: ['math.time.read_to_5_min'],
    curriculumRefs: { ccss: '3.MD.A.1' },
    themeTags: ['time', 'clock', 'elapsed'], sortOrder: 73 },

  // ─── WORD PROBLEMS (contextual practice) ───────────────────────────
  { code: 'math.word_problem.add_within_20', name: 'Word problems (+ within 20)',
    strandCode: 'operations', level: 0.4,
    prereqSkillCodes: ['math.add.within_20.no_crossing'], curriculumRefs: { ccss: '1.OA.A.1' },
    themeTags: ['word_problem', 'add', 'nature'], sortOrder: 60 },
  { code: 'math.word_problem.subtract_within_20', name: 'Word problems (− within 20)',
    strandCode: 'operations', level: 0.45,
    prereqSkillCodes: ['math.subtract.within_20.no_crossing'], curriculumRefs: { ccss: '1.OA.A.1' },
    themeTags: ['word_problem', 'subtract', 'nature'], sortOrder: 61 },
  { code: 'math.word_problem.two_step', name: 'Two-step word problems',
    strandCode: 'operations', level: 0.65,
    prereqSkillCodes: ['math.word_problem.add_within_20', 'math.word_problem.subtract_within_20'],
    curriculumRefs: { ccss: '2.OA.A.1' },
    themeTags: ['word_problem', 'two_step'], sortOrder: 62 },

  // ═══════════════ LEVEL 4 (CCSS grade 4) ═══════════════
  { code: 'math.placevalue.to_1_000_000', name: 'Place value to 1,000,000',
    strandCode: 'place_value', level: 0.86,
    prereqSkillCodes: ['math.placevalue.round_nearest_100'],
    curriculumRefs: { ccss: '4.NBT.A.2' },
    themeTags: ['place_value', 'large_numbers'], sortOrder: 100 },
  { code: 'math.multiply.by_10s_100s', name: 'Multiply by 10s and 100s',
    strandCode: 'multiplication', level: 0.86,
    prereqSkillCodes: ['math.multiply.facts_to_10'],
    curriculumRefs: { ccss: '4.NBT.A.1' },
    themeTags: ['multiply', 'place_value', 'patterns'], sortOrder: 101 },
  { code: 'math.multiply.2digit_by_1digit', name: 'Multiply 2-digit by 1-digit',
    strandCode: 'multiplication', level: 0.87,
    prereqSkillCodes: ['math.multiply.facts_to_10', 'math.multiply.by_10s_100s'],
    curriculumRefs: { ccss: '4.NBT.B.5' },
    themeTags: ['multiply', 'two_digit', 'carrots'], sortOrder: 102 },
  { code: 'math.factors.find', name: 'Factors and multiples',
    strandCode: 'multiplication', level: 0.88,
    prereqSkillCodes: ['math.multiply.facts_to_10', 'math.divide.facts_to_10'],
    curriculumRefs: { ccss: '4.OA.B.4' },
    themeTags: ['multiply', 'divide', 'factors', 'patterns'], sortOrder: 103 },
  { code: 'math.fractions.equivalent', name: 'Equivalent fractions',
    strandCode: 'measurement', level: 0.88,
    prereqSkillCodes: ['math.fractions.compare_visual'],
    curriculumRefs: { ccss: '4.NF.A.1' },
    themeTags: ['fractions', 'compare', 'visual'], sortOrder: 104 },
  { code: 'math.divide.with_remainders', name: 'Division with remainders',
    strandCode: 'multiplication', level: 0.89,
    prereqSkillCodes: ['math.divide.facts_to_10'],
    curriculumRefs: { ccss: '4.NBT.B.6' },
    themeTags: ['divide', 'remainders', 'acorns'], sortOrder: 105 },
  { code: 'math.operations.multi_digit_add_subtract', name: 'Add and subtract large numbers',
    strandCode: 'operations', level: 0.89,
    prereqSkillCodes: ['math.add.within_1000', 'math.subtract.within_1000'],
    curriculumRefs: { ccss: '4.NBT.B.4' },
    themeTags: ['add', 'subtract', 'large_numbers', 'regrouping'], sortOrder: 106 },
  { code: 'math.placevalue.round_large', name: 'Round large numbers',
    strandCode: 'place_value', level: 0.89,
    prereqSkillCodes: ['math.placevalue.to_1_000_000'],
    curriculumRefs: { ccss: '4.NBT.A.3' },
    themeTags: ['rounding', 'place_value', 'large_numbers'], sortOrder: 107 },
  { code: 'math.fractions.add_subtract_like', name: 'Add and subtract fractions (like denominators)',
    strandCode: 'measurement', level: 0.90,
    prereqSkillCodes: ['math.fractions.equivalent'],
    curriculumRefs: { ccss: '4.NF.B.3' },
    themeTags: ['fractions', 'add', 'subtract'], sortOrder: 108 },
  { code: 'math.time.elapsed_across_hours', name: 'Elapsed time across hours',
    strandCode: 'measurement', level: 0.90,
    prereqSkillCodes: ['math.time.elapsed_intervals'],
    curriculumRefs: { ccss: '4.MD.A.2' },
    themeTags: ['time', 'clock', 'elapsed'], sortOrder: 109 },
  { code: 'math.decimals.tenths_hundredths', name: 'Decimals: tenths and hundredths',
    strandCode: 'place_value', level: 0.91,
    prereqSkillCodes: ['math.fractions.equivalent'],
    curriculumRefs: { ccss: '4.NF.C.6' },
    themeTags: ['decimals', 'fractions', 'place_value', 'money'], sortOrder: 110 },
  { code: 'math.multiply.2digit_by_2digit', name: 'Multiply 2-digit by 2-digit',
    strandCode: 'multiplication', level: 0.91,
    prereqSkillCodes: ['math.multiply.2digit_by_1digit'],
    curriculumRefs: { ccss: '4.NBT.B.5' },
    themeTags: ['multiply', 'two_digit'], sortOrder: 111 },
  { code: 'math.decimals.compare', name: 'Compare decimals',
    strandCode: 'place_value', level: 0.92,
    prereqSkillCodes: ['math.decimals.tenths_hundredths'],
    curriculumRefs: { ccss: '4.NF.C.7' },
    themeTags: ['decimals', 'compare'], sortOrder: 112 },
  { code: 'math.measurement.area_perimeter', name: 'Area and perimeter',
    strandCode: 'measurement', level: 0.92,
    prereqSkillCodes: ['math.multiply.2digit_by_1digit'],
    curriculumRefs: { ccss: '4.MD.A.3' },
    themeTags: ['measurement', 'area', 'perimeter', 'garden_beds'], sortOrder: 113 },
  { code: 'math.word_problem.multiplicative', name: 'Comparison word problems (× and ÷)',
    strandCode: 'operations', level: 0.93,
    prereqSkillCodes: ['math.multiply.2digit_by_1digit', 'math.divide.with_remainders'],
    curriculumRefs: { ccss: '4.OA.A.2' },
    themeTags: ['word_problem', 'multiply', 'divide', 'nature'], sortOrder: 114 },

  // ═══════════════ LEVEL 5 (CCSS grade 5) ═══════════════
  { code: 'math.decimals.multiply_divide_10s', name: 'Decimals × and ÷ by 10, 100, 1000',
    strandCode: 'place_value', level: 0.94,
    prereqSkillCodes: ['math.decimals.tenths_hundredths'],
    curriculumRefs: { ccss: '5.NBT.A.2' },
    themeTags: ['decimals', 'place_value', 'patterns'], sortOrder: 120 },
  { code: 'math.fractions.of_a_set', name: 'Fraction of a number',
    strandCode: 'measurement', level: 0.94,
    prereqSkillCodes: ['math.fractions.add_subtract_like', 'math.divide.facts_to_10'],
    curriculumRefs: { ccss: '5.NF.B.4.a' },
    themeTags: ['fractions', 'multiply', 'divide', 'seedlings'], sortOrder: 121 },
  { code: 'math.multiply.multi_digit', name: 'Multiply multi-digit numbers',
    strandCode: 'multiplication', level: 0.95,
    prereqSkillCodes: ['math.multiply.2digit_by_2digit'],
    curriculumRefs: { ccss: '5.NBT.B.5' },
    themeTags: ['multiply', 'large_numbers'], sortOrder: 122 },
  { code: 'math.decimals.add_subtract', name: 'Add and subtract decimals',
    strandCode: 'place_value', level: 0.95,
    prereqSkillCodes: ['math.decimals.compare'],
    curriculumRefs: { ccss: '5.NBT.B.7' },
    themeTags: ['decimals', 'add', 'subtract', 'money'], sortOrder: 123 },
  { code: 'math.divide.long_division', name: 'Long division',
    strandCode: 'multiplication', level: 0.96,
    prereqSkillCodes: ['math.divide.with_remainders'],
    curriculumRefs: { ccss: '5.NBT.B.6' },
    themeTags: ['divide', 'remainders', 'large_numbers'], sortOrder: 124 },
  { code: 'math.fractions.add_subtract_unlike', name: 'Add and subtract fractions (unlike denominators)',
    strandCode: 'measurement', level: 0.96,
    prereqSkillCodes: ['math.fractions.add_subtract_like', 'math.fractions.equivalent'],
    curriculumRefs: { ccss: '5.NF.A.1' },
    themeTags: ['fractions', 'add', 'subtract'], sortOrder: 125 },
  { code: 'math.order_of_operations', name: 'Order of operations',
    strandCode: 'operations', level: 0.97,
    prereqSkillCodes: ['math.multiply.facts_to_10', 'math.add.within_1000'],
    curriculumRefs: { ccss: '5.OA.A.1' },
    themeTags: ['add', 'subtract', 'multiply', 'divide', 'order_of_operations'], sortOrder: 126 },
  { code: 'math.fractions.multiply', name: 'Multiply fractions',
    strandCode: 'measurement', level: 0.98,
    prereqSkillCodes: ['math.fractions.of_a_set'],
    curriculumRefs: { ccss: '5.NF.B.4' },
    themeTags: ['fractions', 'multiply'], sortOrder: 127 },
  { code: 'math.volume.rectangular', name: 'Volume of rectangular prisms',
    strandCode: 'measurement', level: 0.98,
    prereqSkillCodes: ['math.measurement.area_perimeter'],
    curriculumRefs: { ccss: '5.MD.C.5' },
    themeTags: ['measurement', 'volume', 'planter_boxes'], sortOrder: 128 },
  { code: 'math.word_problem.multi_step', name: 'Multi-step word problems',
    strandCode: 'operations', level: 1.0,
    prereqSkillCodes: ['math.word_problem.multiplicative', 'math.operations.multi_digit_add_subtract'],
    curriculumRefs: { ccss: '4.OA.A.3' },
    themeTags: ['word_problem', 'multi_step', 'nature'], sortOrder: 129 },
];
