import type { SkillDefinition } from '@/lib/engine/types';

export const READING_SKILLS: SkillDefinition[] = [
  {
    code: 'reading.sight_words.dolch_primer',
    name: 'Dolch Primer sight words',
    strandCode: 'sight_words',
    level: 0.2,
    prereqSkillCodes: [],
    curriculumRefs: { dolch: 'primer' },
    themeTags: ['sight_words', 'flowers'],
    sortOrder: 1,
  },
  {
    code: 'reading.sight_words.dolch_first_grade',
    name: 'Dolch First Grade sight words',
    strandCode: 'sight_words',
    level: 0.3,
    prereqSkillCodes: ['reading.sight_words.dolch_primer'],
    curriculumRefs: { dolch: 'first_grade' },
    themeTags: ['sight_words', 'bees'],
    sortOrder: 2,
  },
  {
    code: 'reading.phonics.cvc_blend',
    name: 'Blend CVC words',
    strandCode: 'phonics',
    level: 0.2,
    prereqSkillCodes: [],
    curriculumRefs: { og: 'cvc' },
    themeTags: ['phonics', 'cvc', 'ants'],
    sortOrder: 10,
  },
  {
    code: 'reading.phonics.digraphs',
    name: 'Digraphs ch/sh/th',
    strandCode: 'phonics',
    level: 0.3,
    prereqSkillCodes: ['reading.phonics.cvc_blend'],
    curriculumRefs: { og: 'digraphs' },
    themeTags: ['phonics', 'digraphs', 'butterflies'],
    sortOrder: 11,
  },
  {
    code: 'reading.phonics.initial_blends',
    name: 'Initial consonant blends',
    strandCode: 'phonics',
    level: 0.4,
    prereqSkillCodes: ['reading.phonics.digraphs'],
    curriculumRefs: { og: 'blends' },
    themeTags: ['phonics', 'blends', 'frogs'],
    sortOrder: 12,
  },
  {
    code: 'reading.read_aloud.simple',
    name: 'Read a word aloud',
    strandCode: 'phonics',
    level: 0.25,
    prereqSkillCodes: ['reading.phonics.cvc_blend'],
    curriculumRefs: { og: 'oral_reading' },
    themeTags: ['read_aloud', 'practice'],
    sortOrder: 13,
  },
];
